In [17]:
from src.solver import AssetOptionSolver, BarrierAssetOptionSolver, ForexOptionSolver

### Question 1

In [7]:
K=26
S=26
u=1.2
d=1/u
R=1.05
T=3
B=21
barrier_type="down and out"

In [5]:
eu_put = AssetOptionSolver(expire=T,S=S,u=u,d=d,K=K,type="put",style="european",R=R)
eu_put.derivative.grid

[array([1.75836139]),
 array([3.56299545, 0.65778377]),
 array([6.70634921, 1.68831169, 0.        ]),
 array([10.9537037 ,  4.33333333,  0.        ,  0.        ])]

In [6]:
us_put = AssetOptionSolver(expire=T,S=S,u=u,d=d,K=K,type="put",style="american",R=R)
us_put.derivative.grid

[array([2.05849303]),
 array([4.33333333, 0.65778377]),
 array([7.94444444, 1.68831169, 0.        ]),
 array([10.9537037 ,  4.33333333,  0.        ,  0.        ])]

In [13]:
eu_put_barrier = BarrierAssetOptionSolver(expire=T,S=S,u=u,d=d,K=K,type="put",style="european",R=R,B=B,barrier_type=barrier_type)
eu_put_barrier.derivative.premium

np.float64(0.7403626901012624)

In [12]:
us_put_barrier = BarrierAssetOptionSolver(expire=T,S=S,u=u,d=d,K=K,type="put",style="american",R=R,B=B,barrier_type=barrier_type)
us_put_barrier.derivative.premium

np.float64(2.058493033362318)

### Question 3

In [14]:
X = 1/96.65
X

0.010346611484738748

In [16]:
u = 1.06
d = 0.94
T = 3
Rd = 1.08
Rf = 1.09
k = 0.01080
F = 1

In [18]:
eu_call = ForexOptionSolver(expire=T,X=X,F=F,Rf=Rf,Rd=Rd,k=k,u=u,d=d)
eu_call.asset.grid

[array([0.01034661]),
 array([0.00972581, 0.01096741]),
 array([0.00914227, 0.01030936, 0.01162545]),
 array([0.00859373, 0.0096908 , 0.01092793, 0.01232298])]

In [19]:
eu_call.derivative.grid

[array([0.00012337]),
 array([1.96749514e-05, 2.87790046e-04]),
 array([0.00000000e+00, 5.01689952e-05, 6.65552903e-04]),
 array([0.        , 0.        , 0.00012793, 0.00152298])]

In [20]:
eu_put = ForexOptionSolver(expire=T,X=X,F=F,Rf=Rf,Rd=Rd,k=k,u=u,d=d,type="put")
eu_put.derivative.grid


[array([0.00070727]),
 array([0.00109291, 0.000316  ]),
 array([0.0016126 , 0.00059204, 0.        ]),
 array([0.00220627, 0.0011092 , 0.        , 0.        ])]

In [21]:
eu_call.derivative.premium/F*100

np.float64(0.012336518779117442)

In [22]:
eu_put.derivative.premium/F*100

np.float64(0.07072709276836668)

In [23]:
F = 50000000

In [24]:
eu_put_fv = ForexOptionSolver(expire=T,X=X,F=F,Rf=Rf,Rd=Rd,k=k,u=u,d=d,type="put")
eu_put_fv.asset.final

array([429686.49767201, 484540.0931195 , 546396.27521987, 616148.99120538])

In [25]:
eu_put_fv.derivative.premium

np.float64(35363.546384183355)